# Generated by Django 2.2.1 on 2019-05-20 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=30)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('class_name', models.CharField(choices=[('development', 'development'), ('analytics', 'analytics'), ('software', 'software'), ('development analytics', 'development analytics'), ('development software', 'development software'), ('analytics software', 'analytics software')], default='development', max_length=100)),
                ('photo', models.ImageField(upload_to='cert/')),
            ],
        ),
        migrations.CreateModel(
            name='Dev',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=30)),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
